### ISSUE TITLE
Import taking very long

### ISSUE THREAD

**Issue by GittiHab** [findie/wikidata-neo4j-importer#9]
Hello,
we are trying to import a Wikidata dump (from the [19. march 2018](https://dumps.wikimedia.org/wikidatawiki/entities/20180319/)) and it's taking ages: we are at 5% after *one week* now. Do you have any ideas what the issue might be?

This was for concurrency=4 on a 12 core, 256GB machine without an SSD with the script running in Docker (and the Neo4j instance as well).

It seems like that the most time the script itself is idle while Neo4j is doing something (no I/Os though)

**Comment by legraphista** [comment]
Hi @GittiHab,
Thank you for your interest and feedback. We have an optimization branch [here](https://github.com/findie/wikidata-neo4j-importer/tree/optimization) with a few commits towards achieving faster import speed, but it's experimental, and we cannot guarantee its stability. It also requires [apoc](https://github.com/neo4j-contrib/neo4j-apoc-procedures) to be present. Since some time has passed from the last commit, we cannot guarantee it properly works. If there's enough interest regarding this project, I'll dedicate a couple of weekends to update and make it faster.

**Comment by legraphista** [comment]
Regarding the import speed, 5% after a week is indeed out of the standard parameters. 
 
The flow is heavily dependent on indexes. 
As for troubleshooting steps, please make sure that they are present and that Neo4j has enough memory allocated to keep them all in RAM. Make sure that your `ulimit` is properly set as well. You can also go to your Neo4j browser's view and use `:play sysinfo` to inspect `Page Cache` and other present resources that may aid you in uncovering any bottlenecks. 

We haven't tested Neo4j in a Docker environment, so we cannot help you with any advice in that regard.
As a last resort, please take a look at the following docs to check for stuck queries:
https://neo4j.com/docs/operations-manual/current/monitoring/query-management/procedures/#query-management-list-active-locks 
https://neo4j.com/docs/operations-manual/current/monitoring/query-management/procedures/#query-management-list-queries

**Comment by GittiHab** [comment]
@legraphista Thank you 😃, I will try your tips and see if it helps

**Comment by GittiHab** [comment]
So it turns out that it was the index that has been missing which was because I had to restart the input after Neo4j was configured with insufficient memory.

I will post the final configuration once it has successfully imported in case anyone wants to use Docker with the script in the future...

**Comment by GittiHab** [comment]
For anyone having trouble in the future, here a documentation of my steps.

I had two imports running in parallel: One failed due to a deadlock, the other due to a memory overflow. Since I don't need the data from stage 3, I won't worry about this.

This ran on a server as stated above, following the steps after downloading the repo and the dataset:

1. Create a docker network `wikidata_import`
2.  Start a Neo4j Docker container `docker run --network wikidata_import  --env=NEO4J_AUTH=neo4j/password --env=NEO4J_dbms_memory_heap_initial__size=16G --env=NEO4J_dbms_memory_heap_max__size=128G --publish=7474:7474 --publish=7687:7687 --volume=/path/to/database:/data neo4j` (note that the path to the database can be an empty directory)
3. Open the Neo4j browser (`your_ip:7474`) and create the indexes (see the documentation of the script)
4. Check the IP-Address of your Neo4j container in the docker network using `docker network inspect wikidata_import`
5. Navigate to the import script directory and fill in the config.json (you might want to increase the concurrency and disable stage 3)
6. Run the script with `echo "npm install && npm run-script run" | docker run -i --rm -v "$PWD":/usr/src/app --network wikidata_import -w /usr/src/app node:6 /bin/bash`

This allows to run the import script without having neo4j or node installed on the own server.

**TIP:** You might also want to go into the `package.json` and increase the the memory limit of the script. You can simple add `--max_old_space_size=<size>` to the run script. Setting it to 20GB (20480) worked for me – less might also work.
